# Generated by Django 4.1.7 on 2023-02-26 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regionName', models.CharField(max_length=255)),
                ('regionCode', models.IntegerField()),
                ('regionVisited', models.BooleanField()),
            ],
        ),
    ]
