# Generated by Django 4.1.7 on 2023-03-04 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_weather_remove_region_regionvisited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='date',
            field=models.DateField(),
        ),
    ]
