# Generated by Django 4.1.7 on 2023-03-05 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_alter_weather_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='codeInsee',
            field=models.IntegerField(null=True),
        ),
    ]
