# Generated by Django 4.1.6 on 2023-03-04 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currencyCode', models.CharField(max_length=10)),
                ('currencyName', models.CharField(max_length=100)),
                ('icon', models.CharField(max_length=255)),
                ('countryCode', models.CharField(max_length=30)),
                ('countryName', models.CharField(max_length=50)),
                ('currencyRates', models.JSONField(null=True)),
            ],
        ),
    ]
