# Generated by Django 4.1.6 on 2023-03-04 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitcoin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='countryCode',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='currency',
            name='countryName',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='currency',
            name='currencyName',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
